### ISSUE TITLE
下载的pdf显示不全

### ISSUE THREAD

**Issue by happyTonakai** [Kevin0z0/wenquan-pdf-download#1]
感觉貌似是纸张大小设置的问题，图片应该是下载全了，但是在合成pdf的时候有点问题

截图：
https://img.vim-cn.com/3a/73593b12602cab2417cffdc1dd029656502a3a.png

试着下了两本书全都有这种情况，链接 https://lib-nuanxin.wqxuetang.com/#/Book/3209457

浏览器 Edge Chromium, Chrome
系统 Win 10 64 bit

**Comment by Kevin0z0** [comment]
已解决，再试试
