### ISSUE TITLE
学习咨询0.0

### ISSUE THREAD

**Issue by SpongeBob-0614** [Kevin0z0/wenquan-pdf-download#10]
想请教大佬如果想向您一样写出来这样一个厉害的项目需要了解什么方面的知识。。我已经被深深地被震撼和折服了，目前读软件工程，大二0.0

**Comment by Kevin0z0** [comment]
啥？？我不是专业的，我就写着玩的，玩玩ctf应该对你有帮助的

**Comment by SpongeBob-0614** [comment]
谢谢大佬！还想请教个问题0.0 当碰到书title有特殊字符，像是/这种，就添加不了目录。。。

**Comment by SweetInk** [comment]
> 啥？？我不是专业的，我就写着玩的，玩玩ctf应该对你有帮助的

兄弟，你对`IDAPro`应该有了解吧，有问题需要向你请教

**Comment by Lyceik** [comment]
抱歉我不了解0.0没有听过这个东西。。



---原始邮件---
发件人: "SweetInk"<notifications@github.com&gt;
发送时间: 2020年2月9日(周日) 凌晨0:33
收件人: "Kevin0z0/wenquan-pdf-download"<wenquan-pdf-download@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Lyceik"<374506395@qq.com&gt;;
主题: Re: [Kevin0z0/wenquan-pdf-download] 学习咨询0.0 (#10)


 
啥？？我不是专业的，我就写着玩的，玩玩ctf应该对你有帮助的
  
兄弟，你对IDAPro应该有了解吧，有问题需要向你请教

**Comment by Kevin0z0** [comment]
> > 啥？？我不是专业的，我就写着玩的，玩玩ctf应该对你有帮助的
> 
> 兄弟，你对`IDAPro`应该有了解吧，有问题需要向你请教

不太了解，我不怎么搞逆向

**Comment by Kevin0z0** [comment]
> 谢谢大佬！还想请教个问题0.0 当碰到书title有特殊字符，像是/这种，就添加不了目录。。。

我已经更新了，你去看看
