### ISSUE TITLE
大神求助

### ISSUE THREAD

**Issue by dage-liu** [Kevin0z0/wenquan-pdf-download#12]
下载的PDF页面前55-60页正常，后续页面空白，文件大小在38M左右，是什么设置原因吗？使用的火狐油猴

**Comment by Kevin0z0** [comment]
我刚测试了一下火狐，没有异常

**Comment by dage-liu** [comment]
![image](https://user-images.githubusercontent.com/60766854/74005101-d254ca80-49b2-11ea-9576-3da75413ebf1.png)

**Comment by dage-liu** [comment]
您能一次把整本书下载下来吗？
我这不行啊，难道跟网速有关？

**Comment by Kevin0z0** [comment]
已修复，感谢指出问题，请更新0.32版本

**Comment by dage-liu** [comment]
膜拜大神！！
