### ISSUE TITLE
非专业_关于获取目录cookie的问题

### ISSUE THREAD

**Issue by JACKCHEN99** [Kevin0z0/wenquan-pdf-download#14]
- 非常感谢, 刚知道有这个车😊, 想在到期之前下几本感兴趣的书. 

- 书已经下载了2本, 获取目录出现问题(如下图), 可能是我的cookie的HM_开头的2个 没设置(不知道是什么, cookie里也没找到对应的)

![1RZGrj.png](https://s2.ax1x.com/2020/02/08/1RZGrj.png)
![1RZwGT.png](https://s2.ax1x.com/2020/02/08/1RZwGT.png)

**Comment by Kevin0z0** [comment]
你有将下完的书放到exe的目录下吗，这个cookie是没问题的，是你的文件没获取到

**Comment by JACKCHEN99** [comment]
哦, 没有😵, 感谢, 我试试👍

**Comment by JACKCHEN99** [comment]
ok了👍 电子/机械 工业出版社现在关闭了，来清大出版社找几本喜欢的书， 虽然很可能不会看···
