### ISSUE TITLE
windows下 下载到的PDF文件，名称中无法添加英文冒号，导致目录无法成功匹配

### ISSUE THREAD

**Issue by 0xdefs** [Kevin0z0/wenquan-pdf-download#15]
bookID：3207133

**Comment by Kevin0z0** [comment]
已修复，下载release最新版本

**Comment by 0xdefs** [comment]
感谢！py文件调试成功





------------------ 原始邮件 ------------------
发件人: Kevin0z0 <notifications@github.com&gt;
发送时间: 2020年2月8日 18:46
收件人: Kevin0z0/wenquan-pdf-download <wenquan-pdf-download@noreply.github.com&gt;
抄送: Caesar Tong <1548319409@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Kevin0z0/wenquan-pdf-download] windows下 下载到的PDF文件，名称中无法添加英文冒号，导致目录无法成功匹配 (#15)




已修复，下载release最新版本
