### ISSUE TITLE
DPI设置

### ISSUE THREAD

**Issue by yinyue01** [Kevin0z0/wenquan-pdf-download#18]
麻烦问下，下载的PDF的DPI是否可以自定义设置，修改哪里可以设置DPI?

**Comment by yinyue01** [comment]
原始图片DPI好像是96，生成的PDF里DPI为72。我尝试过用图片生成96DPI的PDF，清晰度更高一些。

**Comment by Kevin0z0** [comment]
因为我为了减少一点pdf的体积把保存在pdf里面的图片转成jpg的，你自己去把jpg改成png可能会清楚一点

**Comment by yinyue01** [comment]
改成png后pdf会增大10倍以上；用jpg，只要DPI保持原图的96，生成的pdf整本书大10M左右，清晰度会提高不少。我对比的方式是360浏览器+图片助手下载jpg原图+freepic2pdf.exe生成pdf。只是不知道代码里是怎么设DPI的。



发自我的小米手机在 Kevin0z0 <notifications@github.com>，2020年2月9日 08:43写道：因为我为了减少一点pdf的体积把保存在pdf里面的图片转成jpg的，你自己去把jpg改成png可能会清楚一点



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Kevin0z0/wenquan-pdf-download/issues/18?email_source=notifications\u0026email_token=ACWR57KHZDRTNQNHEPBUJG3RB5GS7A5CNFSM4KR4UEA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELF7LAA#issuecomment-583792000",

"url": "https://github.com/Kevin0z0/wenquan-pdf-download/issues/18?email_source=notifications\u0026email_token=ACWR57KHZDRTNQNHEPBUJG3RB5GS7A5CNFSM4KR4UEA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELF7LAA#issuecomment-583792000",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by yinyue01** [comment]
代码里改成png后pdf会增大10倍以上，清晰度并没有明显提高；用jpg，只要DPI保持原图的96，生成的pdf整本书只大了10M左右，清晰度会提高不少。我对比的方式是“360浏览器+图片助手下载jpg原图+freepic2pdf.exe生成pdf”。只是不知道代码里是怎么设DPI的。另外，脚本生成PDF的过程是否会保存jpg原图，保存的话在哪个路径？

**Comment by yinyue01** [comment]
DPI影响到PDF页面的实际大小，“360浏览器+图片助手下载jpg原图+freepic2pdf.exe生成pdf”方式pdf页面实际大小是你的75%，刚好是72dpi/96dpi，但分辨率提高了，页面实际大小是px/dpi。换个角度，脚本里控制生成pdf页面大小是哪部分呢?
