### ISSUE TITLE
点击下载后一直显示加载中，今天新出现的，换电脑也有

### ISSUE THREAD

**Issue by Turtosoft** [Kevin0z0/wenquan-pdf-download#19]
![QQ截图20200209122846](https://user-images.githubusercontent.com/20209818/74096292-f261c680-4b37-11ea-972c-06aa7d25fe51.png)
正常阅读可以看，审查元素好像是图片改成了base64显示

**Comment by hiouttime** [comment]
一直500，我之前自己写的脚本也不好使

**Comment by lzyfirst** [comment]
是的，他们好像在阅读的时候加入了滑块验证，程序有变，哎~自己又搞不好。

**Comment by dage-liu** [comment]
是的，一直加载中，应该是加了滑块验证，我昨天有一次加载页面弹出过滑块，看来今天上线的完善了。

**Comment by FriedrichWilhelmNietzsche** [comment]
同样"加载中。。。"，升级0.4也是

**Comment by Kevin0z0** [comment]
加了个加密方式，不搞了，等大佬们分析出来白嫖一个，学业繁忙告辞

**Comment by Turtosoft** [comment]
> 加了个加密方式，不搞了，等大佬们分析出来白嫖一个，学业繁忙告辞

我看了下，应该不是加密了，而是把图片的内容数据给base64直接写在网页里了，就不是通过网址引用了

**Comment by Kevin0z0** [comment]
他加了https://lib-nuanxin.wqxuetang.com/v1/read/nvc...  这个文件，先要把这个发出去才能收到图片，刚才python已经实现了，就差分析发出去那串base64是怎么实现的

**Comment by Turtosoft** [comment]
> 他加了https://lib-nuanxin.wqxuetang.com/v1/read/nvc... 这个文件，先要把这个发出去才能收到图片，刚才python已经实现了，就差分析发出去那串base64是怎么实现的

貌似只有浏览到了才会加载。我试过直接把那个带base64的img元素给拷贝到自己本地的网页里，也是能看到那一页的书的内容的。所以可以试试自动滚动网页，加载出一页就抓取一页，碰到滑块条就让用户自己拖一下。就是我不咋懂js，不然就自己改了

**Comment by Kevin0z0** [comment]
晚上我重构一下，有点思路了

**Comment by Turtosoft** [comment]
> 晚上我重构一下，有点思路了
加油！

**Comment by Kevin0z0** [comment]
又能用了

**Comment by sheep111** [comment]
能加载到目录并下载，但是pdf图片是超低清的，还是不行啊

**Comment by Turtosoft** [comment]
> 又能用了

貌似是那个模糊版的图片被放在原来加载成功的图片位置了，所以会识别成已加载，实际上下载出来的pdf是模糊的

**Comment by hiouttime** [comment]
现在文泉加了阿里云的人机验证，用代码绕过成本太大。
建议使用人工/脚本精灵，每滚动一页停顿2秒左右，人工可以看左上角页码变化。
这样会过人机验证，然后可以正常下载。
