### ISSUE TITLE
清晰度不够

### ISSUE THREAD

**Issue by liuquanpu** [Kevin0z0/wenquan-pdf-download#21]
一些专业书籍，保存后PDF是预览图，很不清楚，200页的也只有几MB
比如https://lib-nuanxin.wqxuetang.com/read/pdf/3207229

**Comment by Kevin0z0** [comment]
已经在重构代码了

**Comment by sheep111** [comment]
翻页快了，有的图片还没加载出来就过去了，到后半部分疯狂提示要登陆要刷新的

**Comment by woodyplum** [comment]
翻页太快了, 图片还没清晰显示就过去了, 到结尾再重新来,很多还是不成功, 一个上午不到300页的书没有下来

**Comment by woodyplum** [comment]
可否清晰页面加载完成再翻页

**Comment by SpongeBob-0614** [comment]
请问是点击图片就可以下载吗？为啥我点了没有反应

**Comment by woodyplum** [comment]
等一下就会总动滚动页面了, 大约1-2秒一页

**Comment by SpongeBob-0614** [comment]
> 等一下就会总动滚动页面了, 大约1-2秒一页
请问是等所有页面加载好才会下载吗？我现在一直在滚动
