### ISSUE TITLE
我刚刚点了开始自动滚动，滚到最后一页没反应了

### ISSUE THREAD

**Issue by hxlitong** [Kevin0z0/wenquan-pdf-download#22]
我刚刚点了开始自动滚动，滚到最后一页没反应了
我一看图片是最后一页没加载出来，我往上翻了一下，再回来就加载了，但是没有自动下载，
于是我重新翻到第一页，点了一下就开始滚动了，但是图片都是加载好的

我感觉之前有下载按钮的版本挺好的呀，而且目录也能生成，为啥放弃了

**Comment by Kevin0z0** [comment]
如果是最后一页卡住了你拿鼠标滚轮上下滚一下，不要点
我也不想放弃上一版本啊，他们反爬虫机制太严了

**Comment by hxlitong** [comment]
我再试试，成功了我来报告~~~谢谢

**Comment by woodyplum** [comment]
似乎并不是每次都有保存窗口出来, 而且今天同一本第一次保存前面少了一百多页, 重新下载第二次还是少八九十页, 都是从第一页点击的图片

**Comment by Kevin0z0** [comment]
再等会，新的已经准备好了

**Comment by hxlitong** [comment]
我目前下了3本书都成功了

**Comment by sheep111** [comment]
只要文泉程序员不再搞什么升级，基本这样就可以了

**Comment by cnRicky** [comment]
老哥辛苦了，我们给你众筹生发液！
