### ISSUE TITLE
又失效了

### ISSUE THREAD

**Issue by FriedrichWilhelmNietzsche** [Kevin0z0/wenquan-pdf-download#24]
这是一场程序员间的较量吗？

**Comment by lee4git** [comment]
查找代码里面 width=100 改为 width=160，另外修改生成pdf的方式为直接下载图片，最后合并pdf

**Comment by wlbksy** [comment]
> 查找代码里面 width=100 改为 width=160，另外修改生成pdf的方式为直接下载图片，最后合并pdf

能单独贴一下图片下载的那几行吗

**Comment by kk930604** [comment]
> 查找代码里面 width=100 改为 width=160，另外修改生成pdf的方式为直接下载图片，最后合并pdf

老哥生成PDF直接改下载图片如何修改，求教

**Comment by Kevin0z0** [comment]
我才不是程序员，熟悉熟悉js而已，我不更新了，自己写着玩

**Comment by Turtosoft** [comment]
> 我才不是程序员，熟悉熟悉js而已，我不更新了，自己写着玩

哈哈，我改好了，可以用了。不过就怕发出来又会升级防护手段了

**Comment by FriedrichWilhelmNietzsche** [comment]
> > 我才不是程序员，熟悉熟悉js而已，我不更新了，自己写着玩
> 
> 哈哈，我改好了，可以用了。不过就怕发出来又会升级防护手段了

老哥稳。还有几天就不开放了。。。
