### ISSUE TITLE
被封ip后怎么从指定页面开始下载

### ISSUE THREAD

**Issue by BaldStrong** [Kevin0z0/wenquan-pdf-download#26]
被封ip后怎么从指定页面开始下载

**Comment by Kevin0z0** [comment]
为啥咋还能下。。。直接跳到那一页就行了

**Comment by BaldStrong** [comment]
> 为啥咋还能下。。。直接跳到那一页就行了

我用梯子全局代理就换ip了,就是你这个脚本有没有类似开关的选项?

**Comment by Kevin0z0** [comment]
啥开关。。你如果没下完的话直接跳到断掉的那一页点一下就行了，话说文泉不是只能看30页了嘛
