### ISSUE TITLE
重复下载问题

### ISSUE THREAD

**Issue by bipy** [Kevin0z0/wenquan-pdf-download#6]
下载一个273页的文档 最终生成的pdf有400多页

### Environment: 
Chrome 79.0.3945.130 / Tampermonkey 4.9

### Console Log:

```
 开始下载第47页
 1524
 开始下载第48页
 1885
 开始下载第49页
 1544
 连接出错，开始重新获取 34
 22284
 开始下载第34页
 1321
 开始下载第35页
 1136
 开始下载第36页
 1795
```

由于网站服务器不稳定，运行过程中经常出现，导致有些页被重复下载 拼接

**Comment by Kevin0z0** [comment]
我的并没有什么问题啊![image](https://user-images.githubusercontent.com/24759492/73835220-019af880-4848-11ea-8997-f84a950e2fc6.png)

**Comment by bipy** [comment]
更新了脚本之后问题已解决
