### ISSUE TITLE
每次下载到30页都停止了

### ISSUE THREAD

**Issue by yigerendexiuxing** [Kevin0z0/wenquan-pdf-download#8]
请问作者该怎么解决呢？脑壳疼。

**Comment by Kevin0z0** [comment]
刚测试了一下并没有发现你这样的情况，是不是下载太多被拉黑了，还是有改动过脚本

**Comment by yigerendexiuxing** [comment]
> 刚测试了一下并没有发现你这样的情况，是不是下载太多被拉黑了，还是有植入过脚本

谢谢作者了，原来是要进那个免费的文泉网站才行。
